### ISSUE TITLE
What is the problem please tell me?

### ISSUE THREAD

**Issue by MegaWorldServer** [FusionWowCMS/FusionCMS#4]
Something went wrong:
Fatal error: Uncaught mysqli_sql_exception: BLOB, TEXT, GEOMETRY or JSON column 'location' can't have a default value in C:\xampp\htdocs\install\system.php:250 Stack trace: #0 C:\xampp\htdocs\install\system.php(250): mysqli->query('CREATE TABLE `s...') #1 C:\xampp\htdocs\install\system.php(215): Install->SplitSQL(Resource id #5) #2 C:\xampp\htdocs\install\system.php(19): Install->database() #3 C:\xampp\htdocs\install\system.php(318): Install->__construct() #4 {main} thrown in C:\xampp\htdocs\install\system.php on line 250

Tell me how to fix it?
I just don't really understand it yet

**Comment by Nightprince** [comment]
> Something went wrong: Fatal error: Uncaught mysqli_sql_exception: BLOB, TEXT, GEOMETRY or JSON column 'location' can't have a default value in C:\xampp\htdocs\install\system.php:250 Stack trace: #0 C:\xampp\htdocs\install\system.php(250): mysqli->query('CREATE TABLE `s...') #1 C:\xampp\htdocs\install\system.php(215): Install->SplitSQL(Resource id #5) #2 C:\xampp\htdocs\install\system.php(19): Install->database() #3 C:\xampp\htdocs\install\system.php(318): Install->__construct() #4 {main} thrown in C:\xampp\htdocs\install\system.php on line 250
> 
> Tell me how to fix it? I just don't really understand it yet

What is your MySQL version?

**Comment by MegaWorldServer** [comment]
> > Something went wrong: Fatal error: Uncaught mysqli_sql_exception: BLOB, TEXT, GEOMETRY or JSON column 'location' can't have a default value in C:\xampp\htdocs\install\system.php:250 Stack trace: #0 C:\xampp\htdocs\install\system.php(250): mysqli->query('CREATE TABLE `s...') #1 C:\xampp\htdocs\install\system.php(215): Install->SplitSQL(Resource id #5) #2 C:\xampp\htdocs\install\system.php(19): Install->database() #3 C:\xampp\htdocs\install\system.php(318): Install->__construct() #4 {main} thrown in C:\xampp\htdocs\install\system.php on line 250
> > Tell me how to fix it? I just don't really understand it yet
> 
> What is your MySQL version?

![image](https://github.com/FusionWowCMS/FusionCMS/assets/122090682/4b1f7212-0a4a-4c27-83da-d081428b375e)

**Comment by MegaWorldServer** [comment]
I saw your edit, downloaded it and the installation was successful
